version: '3.8'

services:
  app:
    image: php:8.2-cli
    build: ./backend
    container_name: phase1-app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: phase1-db
    environment:
      MYSQL_DATABASE: beyondchats
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

# version: '3.8'
# services:
#   app:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/var/www
#     depends_on:
#       - db

#   db:
#     image: mysql:8
#     environment:
#       MYSQL_DATABASE: beyondchats
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "3306:3306"



